imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusApiBundle/Resources/config/app/config.yaml" }
    - { resource: "@SyliusPayumBundle/Resources/config/app/config.yaml" }
    - { resource: "@SyliusPayPalPlugin/config/config.yaml" }

parameters:
    fixtures_dir: "%kernel.project_dir%/src/Resources/fixtures"
    sylius_core.public_dir: '%kernel.project_dir%/public'
    sylius.cache:
        type: array

sylius_shop:
    product_grid:
        include_all_descendants: true

sylius_api:
    enabled: true

sylius_theme:
    sources:
        filesystem:
            directories:
                - "%kernel.project_dir%/themes"

sylius_product:
    resources:
        product:
            classes:
                model: App\Entity\Product\Product

sylius_twig_hooks:
    hooks:
        'sylius_admin.base#stylesheets':
            app_styles:
                template: 'admin/stylesheets.html.twig'
        'sylius_admin.base#javascripts':
            app_javascripts:
                template: 'admin/javascripts.html.twig'

        'sylius_shop.base#stylesheets':
            app_styles:
                template: 'shop/stylesheets.html.twig'
        'sylius_shop.base#javascripts':
            app_javascripts:
                template: 'shop/javascripts.html.twig'
