imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusApiBundle/Resources/config/app/config.yaml" }

parameters:
    fixtures_dir: "%kernel.project_dir%/src/Resources/fixtures"
    sylius_core.public_dir: '%kernel.project_dir%/public'
    sylius.cache:
        type: array

sylius_shop:
    product_grid:
        include_all_descendants: true

sylius_api:
    enabled: true

sylius_theme:
    sources:
        filesystem:
            directories:
                - "%kernel.project_dir%/themes"

sylius_ui:
#    events:
#        sylius.admin.login.form.content:
#            blocks:
#                test_credentials:
#                    template: 'Admin/Security/Login/testCredentials.html.twig'
#                    priority: 30

sylius_product:
    resources:
        product:
            classes:
                model: App\Entity\Product\Product

payum:
    storages:
        "%sylius.model.order.class%": { doctrine: orm }
        "%sylius.model.payment.class%": { doctrine: orm }

    security:
        token_storage:
            Sylius\Bundle\PayumBundle\Model\PaymentSecurityToken: { doctrine: orm }

    dynamic_gateways:
        config_storage:
            Sylius\Bundle\PayumBundle\Model\GatewayConfig: { doctrine: orm }

    gateways:
        offline:
            factory: offline
