sylius_twig_hooks:
    hooks:
        'sylius_shop.base.offcanvas':
            info_box:
                template: "info_box.html.twig"
                priority: 100

        'sylius_admin.security.login':
            info_box:
                template: "info_box.html.twig"
                priority: 100

        'sylius_admin.security.login.page.content':
            info_box:
                template: "admin_demo_credentials.html.twig"
                priority: 150

        'sylius_admin.common.index':
            info_box:
                template: "info_box.html.twig"
                priority: 100

        'sylius_shop.base#javascripts':
            analytics:
                template: "analytics.html.twig"
                priority: 100

        'sylius_shop.base#stylesheets':
            override:
                template: "css_override.html.twig"
                priority: -10

        'sylius_admin.base#stylesheets':
            override:
                template: "css_override.html.twig"
                priority: -10

        'sylius_shop.account.login.content.login_container':
            analytics:
                template: "shop_demo_credentials.html.twig"
                priority: 150

        'sylius_shop.homepage.index#metatags':
            homepage_metatags:
                template: "homepage_metatags.html.twig"
                priority: 150

        'sylius_shop.base#metatags':
            homepage_metatags:
                template: "shop_metatags.html.twig"
                priority: 150

        'sylius_shop.homepage.index':
            banner:
                template: '@SyliusShop/homepage/banner.html.twig'
                priority: 300
            latest_deals:
                component: 'sylius_shop:product:list'
                props:
                    limit: 4
                    template: '@SyliusShop/homepage/list_deals.html.twig'
                configuration:
                    title: 'sylius.homepage.latest_deals'
                    test_attribute: 'latest-deals'
                priority: 200
            latest_products:
                component: 'sylius_shop:product:list'
                props:
                    limit: 8
                    template: '@SyliusShop/homepage/list_products.html.twig'
                priority: 0
        'sylius_shop.base.footer.content':
            payment_methods:
                template: 'payment_methods.html.twig'
                priority: 100

